version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4-alpine
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  vote:
    environment:
      - TAG_VOTE=1.0.150
    image: "hutinskit/vote:v${TAG_VOTE}"
    #build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote
 
  result:
    environment:
      - TAG_RESULT=1.0.150
    image: "hutinskit/result:v${TAG_RESULT}"
    #build: ./result
    ports:
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    environment:
      - TAG_WORKER=1.0.150
    image: "hutinskit/worker:v${TAG_WORKER}"
    #build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote
